// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR484mKz5ld9qgJ-D-fB3apDnyT2M0FtM',
    appId: '1:483302109695:web:0e887509b8da4be38237ca',
    messagingSenderId: '483302109695',
    projectId: 'login-d5e5f',
    authDomain: 'login-d5e5f.firebaseapp.com',
    storageBucket: 'login-d5e5f.firebasestorage.app',
    measurementId: 'G-7MPX3G3ZT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm81yQX2xaEhh97pAnv_TKGTbG-39Vqww',
    appId: '1:483302109695:android:fd59bdf381161ea18237ca',
    messagingSenderId: '483302109695',
    projectId: 'login-d5e5f',
    storageBucket: 'login-d5e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3_PHI--M44Rgub8cSHHblnnF35Tt6V4',
    appId: '1:483302109695:ios:7e584c76642484a68237ca',
    messagingSenderId: '483302109695',
    projectId: 'login-d5e5f',
    storageBucket: 'login-d5e5f.firebasestorage.app',
    iosClientId: '483302109695-hkng5gpv2qasdgoahrt24d1belnejcph.apps.googleusercontent.com',
    iosBundleId: 'com.example.campuseyeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3_PHI--M44Rgub8cSHHblnnF35Tt6V4',
    appId: '1:483302109695:ios:7e584c76642484a68237ca',
    messagingSenderId: '483302109695',
    projectId: 'login-d5e5f',
    storageBucket: 'login-d5e5f.firebasestorage.app',
    iosClientId: '483302109695-hkng5gpv2qasdgoahrt24d1belnejcph.apps.googleusercontent.com',
    iosBundleId: 'com.example.campuseyeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR484mKz5ld9qgJ-D-fB3apDnyT2M0FtM',
    appId: '1:483302109695:web:8fab1a04ef6e92078237ca',
    messagingSenderId: '483302109695',
    projectId: 'login-d5e5f',
    authDomain: 'login-d5e5f.firebaseapp.com',
    storageBucket: 'login-d5e5f.firebasestorage.app',
    measurementId: 'G-ZJ25YED76V',
  );
}
